version: '2'

services:
  grafana:
    restart: always
    image: grafana/grafana
    user: "1000" # maybe you dont need this
    ports:
      - 3000:3000
    volumes:
      - ./grafana-data:/var/lib/grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-simple-json-datasource
    links:
      - "miniiot:iot"

  miniiot:
    restart: always
    image: uvwxy/mini-iot-server
    user: "1000" # maybe you dont need this
    volumes:
      - ./data/:/usr/src/app/data/
    ports:
      - 8001:8000

