version: '2'

services:
  app:
    image: uvwxy/mini-iot-server
    volumes:
      - ./data/:/usr/src/app/data/
    ports:
      - 8001:8000
    restart: always

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-simple-json-datasource

volumes:
  grafana-storage:
